In [2]:
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.subplots import make_subplots
import matplotlib.pyplot as plt

In [4]:
#load dataset
path = 'reussite_bac_origine_sociale.csv'
df = pd.read_csv(path, delimiter=';')

In [5]:
# Basic stats
print(f'Number of rows : {df.shape[0]}\n')

print('Display of dataset: ')
display(df.head())

print('Basics statistics :')
data_desc = df.describe(include='all')
display(data_desc)

print('Percentage of missing values: ')
display(100 * df.isnull().sum() / df.shape[0])

missing_values = df.isnull().any().any()
if missing_values :
    print('There are missing values in the dataset')
else :
    print('There are no missing values in the dataset')

Number of rows : 348

Display of dataset:

,Année,Origine sociale,Nombre d'admis au baccalaureat général,Pourcentage d'admis au baccalaureat général,Nombre d'admis au baccalauréat technologique,Pourcentage d'admis au baccalauréat technologique,Nombre d'admis au baccalauréat professionnel,Pourcentage d'admis au baccalauréat professionnel,Nombre d'admis au baccalauréat,Pourcentage d'admis au baccalauréat
0,1997,Autres personnes sans activité professionnelle,8844,66.4,8679,71.2,5883,73.7,23406,69.9
1,1997,Employés,36083,73.9,23852,78.4,12681,81.3,72616,76.5
2,1998,Employés,37362,76.9,26097,80.3,13763,78.1,77222,78.2
3,1998,Ensemble,275113,79.2,144830,79.5,81573,76.7,501516,78.9
4,1998,Indéterminé,4338,64.3,4322,72.4,6488,70.8,15148,69.2

Basics statistics :

,Année,Origine sociale,Nombre d'admis au baccalaureat général,Pourcentage d'admis au baccalaureat général,Nombre d'admis au baccalauréat technologique,Pourcentage d'admis au baccalauréat technologique,Nombre d'admis au baccalauréat professionnel,Pourcentage d'admis au baccalauréat professionnel,Nombre d'admis au baccalauréat,Pourcentage d'admis au baccalauréat
count,348.000000,348,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000
unique,NaN,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Autres personnes sans activité professionnelle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2011.000000,NaN,53213.580460,87.448851,23117.169540,84.602586,23086.853448,81.988506,99417.603448,85.651149
std,8.378647,NaN,82892.404211,8.084476,35759.187672,7.472306,38480.606435,5.825724,153301.782123,7.315427
min,1997.000000,NaN,2923.000000,61.900000,848.000000,66.500000,350.000000,65.400000,4958.000000,67.400000
25%,2004.000000,NaN,7474.000000,82.375000,2695.000000,79.175000,3664.500000,78.675000,16542.250000,80.750000
50%,2011.000000,NaN,24724.000000,88.800000,12583.000000,85.050000,10771.500000,81.750000,56111.500000,86.000000
75%,2018.000000,NaN,49502.500000,94.025000,23709.500000,90.900000,23211.000000,86.125000,93914.500000,91.525000
max,2025.000000,NaN,384158.000000,99.100000,152778.000000,97.600000,190899.000000,94.900000,722971.000000,98.600000

Percentage of missing values:

Année                                                0.0
Origine sociale                                      0.0
Nombre d'admis au baccalaureat général               0.0
Pourcentage d'admis au baccalaureat général          0.0
Nombre d'admis au baccalauréat technologique         0.0
Pourcentage d'admis au baccalauréat technologique    0.0
Nombre d'admis au baccalauréat professionnel         0.0
Pourcentage d'admis au baccalauréat professionnel    0.0
Nombre d'admis au baccalauréat                       0.0
Pourcentage d'admis au baccalauréat                  0.0
dtype: float64

There are no missing values in the dataset

In [6]:
column_feature = ["Origine sociale", "Nombre d'admis au baccalaureat général","Nombre d'admis au baccalauréat technologique", 
                  "Nombre d'admis au baccalauréat professionnel", "Nombre d'admis au baccalauréat"                  ]

fig = make_subplots(rows=3, cols=2)
row = 1
col = 1
for column in column_feature:           
    fig.add_trace(go.Histogram(x=df[column], name=column),row=row, col=col)
    col += 1 
    if col >2:
        row += 1 
        col =1
fig.update_layout(title= dict(text='Distribution', x=0.5))
fig.update_layout(autosize=False, width=1200, height=1000)

fig.show()

In [ ]:
#load dataset
path = 'brevet_etablissement.csv'
df = pd.read_csv(path, delimiter=';')

In [ ]:
# Basic stats
print(f'Number of rows : {df.shape[0]}\n')

print('Display of dataset: ')
display(df.head())

print('Basics statistics :')
data_desc = df.describe(include='all')
display(data_desc)

print('Percentage of missing values: ')
display(100 * df.isnull().sum() / df.shape[0])

missing_values = df.isnull().any().any()
if missing_values :
    print('There are missing values in the dataset')
else :
    print('There are no missing values in the dataset')

Number of rows : 139580

Display of dataset:

,Session,Numero d'etablissement,Type d'etablissement,Patronyme,Secteur d'enseignement,Commune,Libellé commune,Code département,Libellé département,Code académie,...,Code région,Libellé région,Inscrits,Presents,Admis,Admis sans mention,Nombre_d_admis_Mention_AB,Admis Mention bien,Admis Mention très bien,Taux de réussite
0,2012,0920068Z,COLLEGE,MAISON-BLANCHE,PUBLIC,92023,CLAMART,092,HAUTS-DE-SEINE,25,...,10,ILE-DE-FRANCE,240,238,222,71,73,59,19,"93,20%"
1,2012,0920077J,COLLEGE,JEAN PERRIN,PUBLIC,92050,NANTERRE,092,HAUTS-DE-SEINE,25,...,10,ILE-DE-FRANCE,76,69,42,30,10,1,1,"60,80%"
2,2012,0921159K,COLLEGE,EDOUARD MANET,PUBLIC,92078,VILLENEUVE-LA-GARENNE,092,HAUTS-DE-SEINE,25,...,10,ILE-DE-FRANCE,145,140,111,60,31,15,5,"79,20%"
3,2012,0921162N,COLLEGE,LES VALLEES,PUBLIC,92035,LA GARENNE-COLOMBES,092,HAUTS-DE-SEINE,25,...,10,ILE-DE-FRANCE,159,158,143,57,51,21,14,"90,50%"
4,2012,0921239X,COLLEGE,JEAN RENOIR,PUBLIC,92012,BOULOGNE-BILLANCOURT,092,HAUTS-DE-SEINE,25,...,10,ILE-DE-FRANCE,111,110,83,30,28,15,10,"75,40%"

Basics statistics :

,Session,Numero d'etablissement,Type d'etablissement,Patronyme,Secteur d'enseignement,Commune,Libellé commune,Code département,Libellé département,Code académie,...,Code région,Libellé région,Inscrits,Presents,Admis,Admis sans mention,Nombre_d_admis_Mention_AB,Admis Mention bien,Admis Mention très bien,Taux de réussite
count,139580.000000,139580,139580,139479,139580,139580,139580,139580,139580,139580.000000,...,139580.000000,139580,139580.000000,139580.000000,139580.000000,139580.000000,139580.000000,139580.000000,139580.000000,139580
unique,NaN,9608,6,7173,3,4256,4218,102,102,NaN,...,NaN,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1096
top,NaN,0030021G,COLLEGE,-,PUBLIC,31555,TOULOUSE,059,NORD,NaN,...,NaN,ILE-DE-FRANCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"100,00%"
freq,NaN,16,110862,3091,99099,788,788,5555,5555,NaN,...,NaN,19934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8915
mean,2013.537871,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.058762,...,9.515561,NaN,89.774824,88.344440,75.847335,25.431681,21.297550,16.866371,12.251734,NaN
std,4.606661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.327340,...,5.724765,NaN,55.745905,55.125033,49.600904,17.327299,14.867858,14.860492,16.288745,NaN
min,2006.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,...,1.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
25%,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,...,4.000000,NaN,41.000000,40.000000,34.000000,12.000000,10.000000,5.000000,2.000000,NaN
50%,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000,...,10.000000,NaN,87.000000,86.000000,71.000000,22.000000,19.000000,14.000000,7.000000,NaN
75%,2018.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,...,15.000000,NaN,128.000000,126.000000,107.000000,35.000000,29.000000,24.000000,16.000000,NaN
max,2021.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.000000,...,18.000000,NaN,721.000000,719.000000,696.000000,212.000000,238.000000,220.000000,292.000000,NaN

Percentage of missing values:

Session                      0.00000
Numero d'etablissement       0.00000
Type d'etablissement         0.00000
Patronyme                    0.07236
Secteur d'enseignement       0.00000
Commune                      0.00000
Libellé commune              0.00000
Code département             0.00000
Libellé département          0.00000
Code académie                0.00000
Libellé académie             0.00000
Code région                  0.00000
Libellé région               0.00000
Inscrits                     0.00000
Presents                     0.00000
Admis                        0.00000
Admis sans mention           0.00000
Nombre_d_admis_Mention_AB    0.00000
Admis Mention bien           0.00000
Admis Mention très bien      0.00000
Taux de réussite             0.00000
dtype: float64

There are missing values in the dataset